In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [9]:
arr1.ndim

2

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
arr

array([1, 2, 3, 4, 5])

In [12]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [13]:
a = arr

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr[0] = 100

In [18]:
a  # shollow copy

array([100,   2,   3,   4,   5])

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
b = np.copy(arr)

In [22]:
b[0] = 234

In [23]:
b # deep copy

array([234,   2,   3,   4,   5])

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('23 45 56' , sep = ' ')

array([23., 45., 56.])

In [31]:
np.fromstring('23,45,56' , sep = ',')

array([23., 45., 56.])

In [32]:
arr1.ndim

2

In [33]:
arr.ndim

1

In [34]:
arr.size

5

In [35]:
arr1.size

6

In [36]:
arr.shape

(5,)

In [37]:
arr1.shape

(2, 3)

In [38]:
arr1.dtype

dtype('int64')

In [39]:
arr.dtype

dtype('int64')