In [2]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
list(np.arange(0.4,10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [6]:
np.linspace(1,5 ,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [7]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr = np.ones((3,4))

In [10]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [12]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [13]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [15]:
arr1 = np.eye(5)

In [16]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
import pandas as pd
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [19]:
np.random.rand(2,3)

array([[0.40052767, 0.94585131, 0.33443216],
       [0.45309215, 0.14677368, 0.04775602]])

In [21]:
np.random.randn(2,3)

array([[ 0.22257123,  0.13968019,  0.70023706],
       [-1.77799012,  0.13942446,  0.39566136]])

In [22]:
arr2 = np.random.randint(1,5, (3,4))

In [23]:
arr2.size

12

In [24]:
arr2.shape

(3, 4)

In [25]:
arr2.reshape(6,2)

array([[3, 2],
       [2, 4],
       [3, 1],
       [3, 1],
       [3, 2],
       [1, 1]])

In [26]:
arr2.reshape(2,6)

array([[3, 2, 2, 4, 3, 1],
       [3, 1, 3, 2, 1, 1]])

In [27]:
arr2.reshape(4,-1)

array([[3, 2, 2],
       [4, 3, 1],
       [3, 1, 3],
       [2, 1, 1]])

In [28]:
arr1 = np.random.randint(1,10, (5,6))

In [29]:
arr1

array([[9, 8, 1, 7, 2, 5],
       [8, 5, 6, 9, 2, 5],
       [9, 2, 4, 7, 2, 6],
       [1, 9, 2, 6, 2, 9],
       [8, 4, 5, 7, 5, 3]])

In [30]:
arr1>8

array([[ True, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [ True, False, False, False, False, False],
       [False,  True, False, False, False,  True],
       [False, False, False, False, False, False]])

In [31]:
arr1

array([[9, 8, 1, 7, 2, 5],
       [8, 5, 6, 9, 2, 5],
       [9, 2, 4, 7, 2, 6],
       [1, 9, 2, 6, 2, 9],
       [8, 4, 5, 7, 5, 3]])

In [32]:
arr1[arr1 > 8]

array([9, 9, 9, 9, 9])

In [33]:
arr1[0,[0,1]]

array([9, 8])

In [34]:
arr1[2:4 , [2,3]] ## slicing(row) indexing(col)

array([[4, 7],
       [2, 6]])

In [36]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [37]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [38]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [39]:
arr1+arr2

array([[3, 4, 3],
       [2, 3, 2],
       [3, 3, 3]])

In [40]:
arr1-arr2

array([[-1,  0, -1],
       [ 0, -1,  0],
       [ 1,  1, -1]])

In [41]:
arr1*arr2

array([[2, 4, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [42]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [43]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [44]:
arr1@arr2

array([[5, 7, 6],
       [4, 5, 5],
       [7, 9, 8]])

In [45]:
arr1/arr2

array([[0.5, 1. , 0.5],
       [1. , 0.5, 1. ],
       [2. , 2. , 0.5]])

In [46]:
arr/0

/tmp/ipykernel_113/4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [47]:
# numpy broadcasting

In [48]:
arr = np.zeros((3,4))

In [49]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [51]:
a = np.array([1,2,3,4])

In [52]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [57]:
b =  np.array([[3,4,5]])


In [58]:
arr1 = arr+b.T

In [59]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [60]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [61]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [62]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [63]:
np.min(arr1)

3.0

In [64]:
np.max(arr1)

5.0

In [65]:
arr2 = np.random.randint(1,10, (4,4))

In [66]:
arr2

array([[2, 6, 7, 6],
       [5, 9, 5, 7],
       [1, 7, 3, 7],
       [6, 7, 5, 5]])

In [68]:
arr2.reshape(8,2)

array([[2, 6],
       [7, 6],
       [5, 9],
       [5, 7],
       [1, 7],
       [3, 7],
       [6, 7],
       [5, 5]])

In [70]:
arr2.T

array([[2, 5, 1, 6],
       [6, 9, 7, 7],
       [7, 5, 3, 5],
       [6, 7, 7, 5]])

In [73]:
arr2.flatten()

array([2, 6, 7, 6, 5, 9, 5, 7, 1, 7, 3, 7, 6, 7, 5, 5])

In [74]:
arr2

array([[2, 6, 7, 6],
       [5, 9, 5, 7],
       [1, 7, 3, 7],
       [6, 7, 5, 5]])

In [75]:
np.expand_dims(arr2, axis=1)

array([[[2, 6, 7, 6]],

       [[5, 9, 5, 7]],

       [[1, 7, 3, 7]],

       [[6, 7, 5, 5]]])

In [77]:
np.expand_dims(arr2, axis=0)

array([[[2, 6, 7, 6],
        [5, 9, 5, 7],
        [1, 7, 3, 7],
        [6, 7, 5, 5]]])

In [79]:
data = np.array([[1],[2],[3]])

In [80]:
np.squeeze(data)

array([1, 2, 3])

In [81]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [82]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [83]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [84]:
#NUMPY string function

In [85]:
arr = np.array(["sudh","kumar"])

In [86]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [87]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [88]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [89]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [90]:
# Mathmatical function

In [93]:
arr1 = np.random.randint(2,5, (3,4))

In [94]:
arr1

array([[2, 4, 2, 3],
       [3, 2, 3, 4],
       [4, 4, 2, 2]])

In [95]:
np.sin(arr1)

array([[ 0.90929743, -0.7568025 ,  0.90929743,  0.14112001],
       [ 0.14112001,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.7568025 , -0.7568025 ,  0.90929743,  0.90929743]])

In [96]:
np.cos(arr1)

array([[-0.41614684, -0.65364362, -0.41614684, -0.9899925 ],
       [-0.9899925 , -0.41614684, -0.9899925 , -0.65364362],
       [-0.65364362, -0.65364362, -0.41614684, -0.41614684]])

In [97]:
np.tan(arr1)

array([[-2.18503986,  1.15782128, -2.18503986, -0.14254654],
       [-0.14254654, -2.18503986, -0.14254654,  1.15782128],
       [ 1.15782128,  1.15782128, -2.18503986, -2.18503986]])

In [98]:
np.log10(arr1)

array([[0.30103   , 0.60205999, 0.30103   , 0.47712125],
       [0.47712125, 0.30103   , 0.47712125, 0.60205999],
       [0.60205999, 0.60205999, 0.30103   , 0.30103   ]])

In [100]:
np.exp(arr1)

array([[ 7.3890561 , 54.59815003,  7.3890561 , 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692, 54.59815003],
       [54.59815003, 54.59815003,  7.3890561 ,  7.3890561 ]])

In [101]:
np.power(arr1,2)

array([[ 4, 16,  4,  9],
       [ 9,  4,  9, 16],
       [16, 16,  4,  4]])

In [102]:
np.mean(arr1)

2.9166666666666665

In [103]:
np.median(arr1)

3.0

In [104]:
np.std(arr1)

0.8620067027323833

In [105]:
# sort,search and counting function

In [106]:
arr = np.array([4,5,6,7,8,8,9,12,56])

In [107]:
arr

array([ 4,  5,  6,  7,  8,  8,  9, 12, 56])

In [108]:
np.sort(arr)

array([ 4,  5,  6,  7,  8,  8,  9, 12, 56])

In [109]:
np.searchsorted(arr,6)

2

In [110]:
arr1 = np.array([0,345,678,8,8,76,0,0,0,234])

In [111]:
np.count_nonzero(arr1)

6

In [112]:
np.where(arr1 > 0)

(array([1, 2, 3, 4, 5, 9]),)

In [113]:
np.extract(arr1>2,arr1)

array([345, 678,   8,   8,  76, 234])

In [114]:
#Numpy - Byte swapping

In [115]:
arr1

array([  0, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [117]:
arr.byteswap(True)

array([ 288230376151711744,  360287970189639680,  432345564227567616,
        504403158265495552,  576460752303423488,  576460752303423488,
        648518346341351424,  864691128455135232, 4035225266123964416])

In [118]:
arr

array([ 288230376151711744,  360287970189639680,  432345564227567616,
        504403158265495552,  576460752303423488,  576460752303423488,
        648518346341351424,  864691128455135232, 4035225266123964416])

In [119]:
#Numpy copies and views

In [120]:
arr1

array([  0, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [121]:
a = np.copy(arr1)

In [122]:
a[0] = 100

In [123]:
a

array([100, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [124]:
arr1

array([  0, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [125]:
b = arr1.view()

In [126]:
b

array([  0, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [127]:
b[0] = 234

In [128]:
b

array([234, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [129]:
arr1

array([234, 345, 678,   8,   8,  76,   0,   0,   0, 234])

In [130]:
# Numpy - matrix Library

In [131]:
import numpy.matlib as nm

In [132]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [133]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [138]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [135]:
# linear algebra

In [136]:
arr1 =  np.random.randint([[2,3], [4,5]])
arr2 =  np.random.randint([[5,3], [2,5]])

In [137]:
arr1

array([[1, 0],
       [0, 2]])

In [139]:
arr2

array([[3, 2],
       [1, 0]])